apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: metrics-adapter
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.8.2
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:  
    - seriesQuery: '{__name__=~"^container_cpu_usage_seconds_total$",namespace!="",pod_name!="POD",container!="POD"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^container_cpu_usage_seconds_total$"
        as: "cpu_per_second"
      metricsQuery: sum(irate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)
    externalRules:
    - seriesQuery: '{__name__=~"^container_network_receive_packets_total"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: "^container_network_receive_packets_total$"
        as: "guacamole_packets_per_second"
      metricsQuery: sum(increase(container_network_receive_packets_total{namespace!="",pod=~"^guacamole.*"}[1m])) by (namespace)
