apiVersion: v1
kind: Service
metadata:
  name: ing-ctl
  namespace: nginx-ingress
spec:
  type: NodePort
  selector:
    app: nginx-ingress
  ports:
    - port: 80
      nodePort: 31810
      targetPort: 80

